# Villa ngrok configuration
# Start tunnel: ngrok http 3000 --config .ngrok.yml

version: "2"
tunnels:
  villa:
    proto: http
    addr: 3000
    inspect: true
    # Add domain here after setting up:
    # domain: dev-3.villa.cash
