# Digital Ocean App Platform Specification
# Deploy: doctl apps create --spec .do/app.yaml
# Update: doctl apps update <app-id> --spec .do/app.yaml

name: villa

services:
  - name: web
    github:
      repo: rockfridrich/villa
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PUBLIC_PORTO_ENV
        value: stg
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_PORTO_DIALOG_HOST
        value: https://id.porto.sh
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APP_URL
        value: https://villa.ondigitalocean.app
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_CHAIN_ID
        value: "84532"
        scope: RUN_AND_BUILD_TIME

region: nyc
